/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppComingSoonRouteImport } from './routes/app/coming-soon'
import { Route as AppMoreRouteImport } from './routes/app/more'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPlacesRouteImport } from './routes/app/places'
import { Route as AppPrimeRouteImport } from './routes/app/prime'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppTomorrowRouteImport } from './routes/app/tomorrow'
import { Route as AppWaitingRouteImport } from './routes/app/waiting'
import { Route as AppPackingIndexRouteImport } from './routes/app/packing/index'
import { Route as AppPackingListIdRouteImport } from './routes/app/packing/$listId'
import { Route as AppShoppingIndexRouteImport } from './routes/app/shopping/index'
import { Route as AppShoppingListIdRouteImport } from './routes/app/shopping/$listId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComingSoonRoute = AppComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrimeRoute = AppPrimeRouteImport.update({
  id: '/prime',
  path: '/prime',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTomorrowRoute = AppTomorrowRouteImport.update({
  id: '/tomorrow',
  path: '/tomorrow',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWaitingRoute = AppWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPackingIndexRoute = AppPackingIndexRouteImport.update({
  id: '/packing/',
  path: '/packing/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPackingListIdRoute = AppPackingListIdRouteImport.update({
  id: '/packing/$listId',
  path: '/packing/$listId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShoppingIndexRoute = AppShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShoppingListIdRoute = AppShoppingListIdRouteImport.update({
  id: '/shopping/$listId',
  path: '/shopping/$listId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/prime': typeof AppPrimeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/tomorrow': typeof AppTomorrowRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app/': typeof AppIndexRoute
  '/app/packing/$listId': typeof AppPackingListIdRoute
  '/app/shopping/$listId': typeof AppShoppingListIdRoute
  '/app/packing/': typeof AppPackingIndexRoute
  '/app/shopping/': typeof AppShoppingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/prime': typeof AppPrimeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/tomorrow': typeof AppTomorrowRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app': typeof AppIndexRoute
  '/app/packing/$listId': typeof AppPackingListIdRoute
  '/app/shopping/$listId': typeof AppShoppingListIdRoute
  '/app/packing': typeof AppPackingIndexRoute
  '/app/shopping': typeof AppShoppingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/prime': typeof AppPrimeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/tomorrow': typeof AppTomorrowRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app/': typeof AppIndexRoute
  '/app/packing/$listId': typeof AppPackingListIdRoute
  '/app/shopping/$listId': typeof AppShoppingListIdRoute
  '/app/packing/': typeof AppPackingIndexRoute
  '/app/shopping/': typeof AppShoppingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/coming-soon'
    | '/app/more'
    | '/app/notifications'
    | '/app/places'
    | '/app/prime'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/app/tomorrow'
    | '/app/waiting'
    | '/app/'
    | '/app/packing/$listId'
    | '/app/shopping/$listId'
    | '/app/packing/'
    | '/app/shopping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/coming-soon'
    | '/app/more'
    | '/app/notifications'
    | '/app/places'
    | '/app/prime'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/app/tomorrow'
    | '/app/waiting'
    | '/app'
    | '/app/packing/$listId'
    | '/app/shopping/$listId'
    | '/app/packing'
    | '/app/shopping'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/coming-soon'
    | '/app/more'
    | '/app/notifications'
    | '/app/places'
    | '/app/prime'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/app/tomorrow'
    | '/app/waiting'
    | '/app/'
    | '/app/packing/$listId'
    | '/app/shopping/$listId'
    | '/app/packing/'
    | '/app/shopping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/coming-soon': {
      id: '/app/coming-soon'
      path: '/coming-soon'
      fullPath: '/app/coming-soon'
      preLoaderRoute: typeof AppComingSoonRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/places': {
      id: '/app/places'
      path: '/places'
      fullPath: '/app/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/prime': {
      id: '/app/prime'
      path: '/prime'
      fullPath: '/app/prime'
      preLoaderRoute: typeof AppPrimeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tomorrow': {
      id: '/app/tomorrow'
      path: '/tomorrow'
      fullPath: '/app/tomorrow'
      preLoaderRoute: typeof AppTomorrowRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/waiting': {
      id: '/app/waiting'
      path: '/waiting'
      fullPath: '/app/waiting'
      preLoaderRoute: typeof AppWaitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/packing/': {
      id: '/app/packing/'
      path: '/packing'
      fullPath: '/app/packing/'
      preLoaderRoute: typeof AppPackingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/packing/$listId': {
      id: '/app/packing/$listId'
      path: '/packing/$listId'
      fullPath: '/app/packing/$listId'
      preLoaderRoute: typeof AppPackingListIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shopping/': {
      id: '/app/shopping/'
      path: '/shopping'
      fullPath: '/app/shopping/'
      preLoaderRoute: typeof AppShoppingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shopping/$listId': {
      id: '/app/shopping/$listId'
      path: '/shopping/$listId'
      fullPath: '/app/shopping/$listId'
      preLoaderRoute: typeof AppShoppingListIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppComingSoonRoute: typeof AppComingSoonRoute
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppPrimeRoute: typeof AppPrimeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTomorrowRoute: typeof AppTomorrowRoute
  AppWaitingRoute: typeof AppWaitingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPackingListIdRoute: typeof AppPackingListIdRoute
  AppShoppingListIdRoute: typeof AppShoppingListIdRoute
  AppPackingIndexRoute: typeof AppPackingIndexRoute
  AppShoppingIndexRoute: typeof AppShoppingIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppComingSoonRoute: AppComingSoonRoute,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppPrimeRoute: AppPrimeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTomorrowRoute: AppTomorrowRoute,
  AppWaitingRoute: AppWaitingRoute,
  AppIndexRoute: AppIndexRoute,
  AppPackingListIdRoute: AppPackingListIdRoute,
  AppShoppingListIdRoute: AppShoppingListIdRoute,
  AppPackingIndexRoute: AppPackingIndexRoute,
  AppShoppingIndexRoute: AppShoppingIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
