/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPackingRouteImport } from './routes/app/packing'
import { Route as AppPlacesRouteImport } from './routes/app/places'
import { Route as AppShoppingRouteImport } from './routes/app/shopping'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppWaitingRouteImport } from './routes/app/waiting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPackingRoute = AppPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWaitingRoute = AppWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/packing': typeof AppPackingRoute
  '/app/places': typeof AppPlacesRoute
  '/app/shopping': typeof AppShoppingRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/packing': typeof AppPackingRoute
  '/app/places': typeof AppPlacesRoute
  '/app/shopping': typeof AppShoppingRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/packing': typeof AppPackingRoute
  '/app/places': typeof AppPlacesRoute
  '/app/shopping': typeof AppShoppingRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/waiting': typeof AppWaitingRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/packing'
    | '/app/places'
    | '/app/shopping'
    | '/app/tasks'
    | '/app/waiting'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/packing'
    | '/app/places'
    | '/app/shopping'
    | '/app/tasks'
    | '/app/waiting'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/packing'
    | '/app/places'
    | '/app/shopping'
    | '/app/tasks'
    | '/app/waiting'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/packing': {
      id: '/app/packing'
      path: '/packing'
      fullPath: '/app/packing'
      preLoaderRoute: typeof AppPackingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/places': {
      id: '/app/places'
      path: '/places'
      fullPath: '/app/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shopping': {
      id: '/app/shopping'
      path: '/shopping'
      fullPath: '/app/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/waiting': {
      id: '/app/waiting'
      path: '/waiting'
      fullPath: '/app/waiting'
      preLoaderRoute: typeof AppWaitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppPackingRoute: typeof AppPackingRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppShoppingRoute: typeof AppShoppingRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWaitingRoute: typeof AppWaitingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPackingRoute: AppPackingRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppShoppingRoute: AppShoppingRoute,
  AppTasksRoute: AppTasksRoute,
  AppWaitingRoute: AppWaitingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
